config/routes.rb
Fett::Application.routes.draw do

  root :to => "home#index"
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :employer do
    resources :jobs
    resource :profile
  end
  resources :employees
  resources :jobs
  resources :profiles
  resources :resume do
    resources :work_histories
  end
  resources :work_histories
  
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout" }

  devise_for :employees, :skip => :sessions
  devise_for :employers, :skip => :sessions
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/employee.rb
class Employee < User
	has_one :resume, :dependent => :destroy

	attr_accessible :resume_attributes

	accepts_nested_attributes_for :resume
end

app/models/employer.rb
class Employer < User
	has_many :jobs, :dependent => :destroy
	has_one :profile, :dependent => :destroy
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :employer
	JOB_TYPES = %w[Permanent Contract]

  include Tire::Model::Search
  include Tire::Model::Callbacks

  def self.search(params)
    if Job.count > 0
      tire.search(load: true) do
        query { string params[:query] } if params[:query].present?
        sort { by :created_at, "desc" } if params[:query].blank?
      end
    else 
      scoped
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :employer
end

app/models/resume.rb
class Resume < ActiveRecord::Base
	validates_presence_of :first_name, :last_name, :nationality, :status, :language, :address

	has_many :work_histories, dependent: :destroy
	belongs_to :employee

	accepts_nested_attributes_for :work_histories, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :type, 
  :name, :address, :telephone, :url, :image

  mount_uploader :image, ImageUploader

  USER_TYPES = %w[Employee Employer]

	after_create :create_profile, if: Proc.new { |u|  u.type == 'Employer' }
  after_create :create_resume, if: proc { |u| u.type == 'Employee' } 

  def create_profile
    profile = Profile.new
    profile.employer_id = self.id
    profile.save
  end

  def create_resume
    resume = Resume.new
    resume.employee_id = self.id
    resume.save
  end
end

app/models/work_history.rb
class WorkHistory < ActiveRecord::Base
	validates_presence_of :company_name, :start_date, :job_description

	belongs_to :resume

  attr_accessible :company_name, :end_date, :job_description, :start_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def edit
		@employee = Employee.find(params[:id])
	end

	  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      redirect_to edit_employee_path(@employee)
    else
      render action: 'edit'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = Job.search(params)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :create, :destroy, :update]
  def index
    @employer = get_employer(params[:employer_id])
    @jobs = @employer.jobs
    #@jobs = Job.all
  end

  def show
    @job = Job.where(id: params[:id]).first
  end

  def new
    if current_user
      @employer = get_employer(params[:employer_id])
      @job = @employer.jobs.build
    else 
      @job = Job.new
    end
  end

  def create
    @employer = get_employer(params[:employer_id])
    @job = @employer.jobs.build(params[:job])
    if @job.save
      redirect_to root_path
    else
      render :action => "new"
    end
  end

  def edit
    @employer = get_employer(params[:employer_id])
    @job = @employer.jobs.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
       redirect_to job_path(@job)
    else
       render :action => 'edit'
    end
  end

  def delete
    Job.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def get_employer(employer_id)
    Employer.where(id: params[:employer_id]).first
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end
  def show
    @profile = get_employer(params[:employer_id])
    @profile = @employer.profile
  end
  def new
  end
  def create
  end
  def edit
    @employer = get_employer(params[:employer_id])
    @profile = @employer.profile
  end
  def update
    @employer = get_employer(params[:employer_id])
    @profile = @employer.profile
    if @profile.update_attributes(params[:profile])
      redirect_to edit_employer_profile_path(@employer)
    else
      render :action => "edit"
    end
  end
  def delete
  end

  private
  def get_employer(employer_id)
    Employer.where(id: employer_id).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_link(link_text, link_path)
		class_name = current_page?(link_path) ? 'active' : ''

		content_tag(:dd) do
			link_to(link_text, link_path, class: class_name)
		end
	end

  def flash_class(name)
    if name == :error or name == :alert
      'error'
    elsif name == :notice or name == :success
      'success'
    end
  end

  def image_avatar(avatar, show, width)
    if avatar.image_url.nil?
      if !show.blank?
        image_tag "avatar/guest_avatar.gif"
      end
    else 
      image_tag avatar.image_url.to_s, width: width
    end
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def avatar_account(width)
    if current_user.image_url.nil?
      image_tag "avatar/guest_avatar.gif"
    else
      image_tag current_user.image_url.to_s, :width => width
    end
  end
end

app/views/employees/edit.html.erb
<div class="row">
  <div class="twelve columns">
    <h4 class="edit-header">Edit Resume</h4>
  </div>
</div>
<%= render "devise/menu/edit_nav_bar_items" %>
<%= form_for @employee, :html => { :class => "nice"} do |f| %>
  <div class="row">
    <div class="twelve columns">
      <div class="six columns" >
        <div class='panel'>
        <%= f.fields_for :resume do |g| %>
          <ul class="form-field ">
            <li>
              <%= g.label :first_name, id: "text" %>
              <%= g.text_field "first_name", class: "input-text required", placeholder: "ex: Steve" %>
              <%= g.label :last_name, id: "text" %>
              <%= g.text_field "last_name", class: "input-text required", placeholder: "ex: Jobs"  %>
              <%= g.label :date_of_birth, id: "text" %>
              <%= g.text_field "dateofbirth",  class: "input-text required", placeholder: "ex: 1955-02-24" %>        	
              <%= g.label :nationality, id: "text" %>
              <%= g.text_field "nationality", class: "input-text required", placeholder: "ex: American" %>
              <%= g.label :status, id: "text" %>
              <%= select( :resume , "status" ,%w[Single Married Divorce]) %>
              <%= g.label :language, id: "text" %>
              <%= g.text_field "language", class: "input-text required", placeholder: "ex: America" %>
              <%= g.label :address, id: "text" %>
              <%= g.text_area "address", class: "input-text required", placeholder: "ex: Apple Campus, 1 Infinite Loop, Cupertino, California, United States" %>
            </li>
          </ul>
        </div>
      </div>
      <div class="six columns" >
        <ul id='work-history' class="form-field ">
          <%= g.fields_for :work_histories, :html => { :class => "panel"} do |w| %>
          <li>
            <div class="panel">
              <%= w.label :company_name %>
              <%= w.text_field :company_name, class: "input-text required", placeholder: "ex: Apple Inc."  %>
              <%= w.label :start_date %>
              <%= w.text_field :start_date, class: "datepicker input-text required", placeholder: "ex: 1977-01-03"  %><br/>
              <%= w.label :end_date %>
              <%= w.text_field :end_date, class: "datepicker input-text", placeholder: "ex: 2011-10-05"   %><br/>
              <%= w.label :job_description %>
              <%= w.text_field :job_description, class: "input-text required", placeholder: "ex: ICEO"  %>
              <%= w.hidden_field :_destroy, class: 'destroy' %>
              <%= link_to "Remove", '#', class: 'remove' %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="description five columns offset-by-one">
        <%= link_to "Back", :back, :class => "medium button radius" %>
        <%= f.submit "Update", :class => "medium button radius" %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="row">
  <div class="nine columns">
  <%= form_tag root_path, method: :get, class: "nice" do %>
    <%= text_field_tag :query, params[:query], class: "input-text", placeholder: "Search" %>
  <% end -%>
  </div>
  <div class="three columns">
    <div class="right">
      <%= link_to "Post a job", new_employer_jobs_path(current_user), :class => "medium button radius" if current_user and current_user.type == 'Employer' %>
    </div>
  </div>
</div>
<div class="jobs-listing">
  <div class="row">
    <div class="twelve columns">
      <h4>Recent Jobs</h4>
      <ul>
        <% if @jobs.each do |j| %>
          <%= content_tag_for :li, j do %>
            <%= link_to job_path(j) do %>
            <% if j.created_at > Time.now - 1.days %>
            <span class="green radius label">new</span>
            <% elsif j.updated_at > Time.now - 1.days %>
            <span class="white radius label">update</span>
            <% end -%>
            <span class="job location"><b><%= j.location %></b></span>
            <span class="job title"><u><%= j.title %></u></span> <%= 'at' if j.employer.profile.name.present? %>
            <span class="job company"><%= j.employer.profile.name %></span>
            <span class="date"><%= j.created_at.strftime('%b %d') %></span>
            <span class="job salary"><%= j.salary %></span>
            <% end %>
          <% end %>

        <% end.empty? %>
         -> No matches found.
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/jobs/edit.html.erb
<% title "Edit Job" %>
<div class="row">
  <div class="twelve columns">
    <%= link_to "Back to job", :back %>
    <h4 class="edit-header">Edit your Job</h4>
  </div>
</div>

<div class="row">
  <div class="seven columns">
    <h5 class="job-header">tell us about the position</h5>
    <%= form_for [@employer, @job], url: { action: "update" }, html: { class: 'edit_job nice'} do |f| %>
      <table width="100%" cellpadding="0" cellspacing="0">
        <tbody>
          <tr>
            <td><%= f.label :title, "Job Title" %></td>
            <td><%= f.text_field :title, :class => "input-text" %>"Reception" or "Cook"</td>
          </tr>
          <tr>
            <td><%= f.label :job_type %></td>
            <td><%= f.select :job_type, Job::JOB_TYPES, :width => "300" %></td>
          </tr>
          <tr>
            <td><%= f.label :location %></td>
            <td><%= f.text_field :location, :class => "input-text" %>"Phra Khanong, Bangkok", "Chaing Mai" or "Thailand"</td>
          </tr>
          <tr>
            <td><%= f.label :salary %></td>
            <td><%= f.text_field :salary, :class => "input-text" %>"800 /day", "20,000 /m" or "20,000-30,000 /m"</td>
          </tr>
         </tbody>
      </table>
    <div class="description">
      <%= f.label :description do %>
        Description
        <span class="right">Format text with <%= link_to "Textile", "http://en.wikipedia.org/wiki/Textile_(markup_language)", target: "_blank" %></span>
      <% end %>
      <%= f.text_area :description, :size => "60x18" %>

      <%= link_to "Back", :back, :class => "button radius" %>
      <%= f.submit "Update", :class => "medium button radius" %>
    </div>
    <% end %>
  </div>
  <div class="three columns offset-by-one company-detail">
    <ul>
      <li><h5><%= @job.employer.profile.name %></h5></li>
      <li><%= image_avatar(@job.employer, true, '190') %></li>
      <li><hr></li>
      <li><%= @job.employer.profile.address %></li>
      <li><%= @job.employer.profile.telephone %></li>
      <li><%= link_to @job.employer.email, "emailto:" + @job.employer.email %></li>
      <li><%= link_to @job.employer.profile.url if @job.employer.profile.url.present? %></li>
    </ul>
  </div>
</div>

app/views/jobs/index.html.erb
<% title "listing" %>
<div class="row">
  <div class="twelve columns">
    <h4 class="edit-header">Jobs Listing</h4>
  </div>
</div>

<%= render "devise/menu/edit_nav_bar_items" %>

<div class="row">
  <div class="twelve columns">
    <%= link_to "Post job", new_job_path %><br />

    <% if @jobs.each do |j| %>
      <b><%= j.location %></b> <u><%= j.title %></u> at <%= j.employer.email %> Salary: <%= j.salary %> <%= link_to 'view job', j %><br />
    <% end.empty? %>
      empty
    <% end %>
  </div>
</div>

app/views/jobs/new.html.erb
<% title "Post Job" %>
<div class="row">
  <div class="twelve columns">
    <%= link_to "Back to jobs listing", :back %>
    <h4 class="edit-header">Step 1: Post your Job</h4>
  </div>
</div>

<div class="row">
  <div class="seven columns">
    <h5 class="job-header">tell us about the position</h5>
    <%= form_for [@employer, @job], html: { class: 'new_job nice'} do |f| %>
      <table width="95%" cellpadding="0" cellspacing="0">
        <tbody>
          <tr>
            <td><%= f.label :title, "Job Title" %></td>
            <td><%= f.text_field :title, :class => "input-text" %>"Reception" or "Cook"</td>
          </tr>
          <tr>
            <td><%= f.label :job_type %></td>
            <td><%= f.select :job_type, Job::JOB_TYPES, :width => "300" %></td>
          </tr>
          <tr>
            <td><%= f.label :location %></td>
            <td><%= f.text_field :location, :class => "input-text" %>"Phra Khanong, Bangkok", "Chaing Mai" or "Thailand"</td>
          </tr>
          <tr>
            <td><%= f.label :salary %></td>
            <td><%= f.text_field :salary, :class => "input-text" %>"800 /day", "20,000 /m" or "20,000-30,000 /m"</td>
          </tr>
        </tbody>
      </table>
      <div class="description">
        <%= f.label :description do %>
          Description
          <span class="right">Format text with <%= link_to "Textile", "http://en.wikipedia.org/wiki/Textile_(markup_language)", target: "_blank" %></span>
        <% end %>
        <%= f.text_area :description, :size => "60x18" %>

        <%= f.submit "Publish", :class => "medium button radius" %>
      </div>
    <% end %>
  </div>
  <div class="three columns offset-by-one company-detail">
    <ul>
      <li><h5><%= @employer.profile.name %></h5></li>
      <li><%= image_avatar(current_user, true, '190') %></li>
      <li><hr></li>
      <li><%= @employer.profile.address %></li>
      <li><%= @employer.profile.telephone %></li>
      <li><%= @employer.email %></li>
      <li><%= link_to @employer.profile.url if @employer.profile.url.present?%></li>
    </ul>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="row">
  <div class="twelve columns">
      <% if @job.employer == current_user and current_user.type == 'Employer' %>
      <p class="right"><%= link_to "Edit job", edit_employer_job_path(current_user) %></p>
      <% end %>
      <p><%= link_to "Back to jobs listing", root_path %></p>
  </div>
</div>

<div class="row">
  <hr>
</div>

<div class="row">
  <div class="nine columns">
    <div class="pad">
      <h4><%= @job.title %></h4>
      <p><medium>Posted <%= @job.created_at.strftime('%b %d') %></medium></p>
      
      <h6><strong><%= @job.employer.profile.name %></strong><br />
      Location: <%= @job.location %><br />
      <%= link_to @job.employer.profile.url, @job.employer.profile.url if @job.employer.profile.url.present? %></h6>
    </div>
  </div>
  <div class="three columns">
    <%= image_avatar(@job.employer, false, '150') %>
  </div>
</div>

<div class="row">
  <hr>
</div>

<div class="row job">
  <div class="nine columns">
    <div class="job-description pad"><%= RedCloth.new(@job.description).to_html.html_safe %></div>
  </div>
  <div class="three columns">
    <ul class="job-aside">
      <li class="top"><strong>Salary</strong> <%= @job.salary %></li>
      <li><strong>Job Type</strong> <%= @job.job_type %></li>
    </ul>
    <%= link_to "Add to shortlist", '', :class => "button radius" %>
  </div>
</div>

<div class="row">
  <div class="job apply">
    <div class="six columns">
      <h5>Apply for this position</h5><br />
      <%= link_to "Apply now", "", :class => "button radius" %>
    </div>
    <div class="six columns">
      <h5>Company Information</h5>
      <b>Email</b> <%= @job.employer.email %><br />
      <b>Telephone</b> <%= @job.employer.profile.telephone %><br />
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Board | <%= content_for?(:title) ? yield(:title) : "artellectual" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_include_tag :application %>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="container">
        <div class="row">
          <div class="eight columns">
            <h1><%= link_to "Job Board", root_path %></h1>
          </div>
          <div class="four columns">
            <%= render 'devise/menu/registration_items' %>
          </div>
        </div>
      </div>
    </header>
    <div class="row">
      <div class="twelve columns">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, :class => "#{flash_class(name)} alert-box") do %>
            <%= msg %>
            <%= link_to("x", "", :class => "close") %>
          <% end %>
        <% end %>
      </div>
    </div>
    <% #<%= content_tag :h1, yield(:title) if show_title? %>
    <div class="container">
      <%= yield %>
    </div>
    <footer class="row">
      <section class="twelve columns">
        <p class="right">artellectual.com</p>
      </section>
    </footer>
  </body>
</html>

app/views/profiles/edit.html.erb
<script>
  $(function() {
    $( "#datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true
    });
  });
</script>
<div class="row">
  <div class="twelve columns">
    <h4 class="edit-header">Edit Profile</h4>
  </div>
</div>

<%= render "devise/menu/edit_nav_bar_items" %>

<div class="row">
  <div class="seven columns">
      <%= form_for [@employer, @profile], html: { class: 'edit_profile nice' } do |f| %>
      <table width="100%" cellpadding="0" cellspacing="0">
        <tbody>
          <tr>
            <td><%= f.label "name" %></td>
            <td><%= f.text_field "name", class: "input-text" %></td>
          </tr>
          <tr>
            <td><%= f.label "address" %></td>
            <td><%= f.text_field "address", class: "input-text" %></td>
          </tr>
          <tr>
            <td><%= f.label "telephone" %></td>
            <td><%= f.text_field "telephone", class: "input-text" %></td>
          </tr>
          <tr>
            <td><%= f.label "url", "URL" %></td>
            <td><%= f.text_field "url", class: "input-text" %></td>
          </tr>
         </tbody>
      </table>
      <div class="description">
        <%= f.label :description do %>
          Description
          <span class="right">Format text with <%= link_to "Textile", "http://en.wikipedia.org/wiki/Textile_(markup_language)", target: "_blank" %></span>
        <% end %>
        <%= f.text_area :description, :size => "60x18" %>
    
        <%= link_to "Back", :back, :class => "medium button radius" %>
        <%= f.submit "Update", :class => "medium button radius" %>
      </div>
      <% end %>
  </div>
  <div class="three columns offset-by-one company-detail">
    <ul>
      <li><h5><%= @employer.profile.name %></h5></li>
      <li><%= image_avatar(current_user, true, '190') %></li>
      <li><hr></li>
      <li><%= @employer.profile.address %></li>
      <li><%= @employer.profile.telephone %></li>
      <li><%= link_to @employer.profile.url if @employer.profile.url.present? %></li>
    </ul>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="row">
  <div class="twelve columns content">
    show
  </div>
</div>